# Generated by Django 3.1.2 on 2020-10-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizer',
            options={'ordering': ['type'], 'verbose_name_plural': 'Fertilizers'},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['alias'], 'verbose_name_plural': 'Tanks'},
        ),
    ]
